USE
ROLE TRAINING_ROLE;
USE
WAREHOUSE NUTRIRAG_PROJECT;
USE
DATABASE NUTRIRAG_PROJECT;
USE
SCHEMA ANALYTICS;

CREATE OR REPLACE PROCEDURE NUTRIRAG_PROJECT.ANALYTICS.LOG_TRANSFORMATION("CONV_ID" VARCHAR, "USER_ID" VARCHAR, "FULL_RESPONSE" VARIANT, "ORIGINAL_RECIPE" VARIANT)
RETURNS BOOLEAN
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
    INSERT INTO NUTRIRAG_PROJECT.ANALYTICS.HIST_TRANSFORMATIONS (
        CONVERSATION_ID,
        USER_ID,
        ORIGINAL_NAME,
        TRANSFORMED_NAME,
        SUCCESS,
        MESSAGE,
        NUTRITION_BEFORE,
        NUTRITION_AFTER,
        SUBSTITUTIONS,
        ORIGINAL_RECIPE,
        NEW_RECIPE,
        FULL_RESPONSE_JSON
    )
    SELECT
        :CONV_ID,
        :USER_ID,
        :FULL_RESPONSE:original_name::STRING,
        :FULL_RESPONSE:transformed_name::STRING,
        :FULL_RESPONSE:success::BOOLEAN,
        :FULL_RESPONSE:message::STRING,
        :FULL_RESPONSE:nutrition_before,
        :FULL_RESPONSE:nutrition_after,
        :FULL_RESPONSE:substitutions,
        :ORIGINAL_RECIPE,
        :FULL_RESPONSE:recipe,
        :FULL_RESPONSE;

    RETURN TRUE;

EXCEPTION
    WHEN OTHER THEN
        RETURN FALSE;
END;
';
