"""Snowflake table definitions for CLEANED_INGREDIENT table."""


from shared.snowflake.tables.table import define_snowflake_table, Table


@define_snowflake_table(
    SNOWFLAKE_DATABASE="NUTRIRAG_PROJECT",
    SCHEMA_NAME="RAW",
    TABLE_NAME="CLEANED_INGREDIENTS",
)
class CleanedIngredients(Table):
    NDB_NO = "NDB_NO"
    CALCIUM_MG = "CALCIUM_MG"
    CARB_G = "CARB_G"
    COPPER_MCG = "COPPER_MCG"
    DESCRIP = "DESCRIP"
    ENERGY_KCAL = "ENERGY_KCAL"
    FAT_G = "FAT_G"
    FIBER_G = "FIBER_G"
    FOLATE_MCG = "FOLATE_MCG"
    IRON_MG = "IRON_MG"
    MAGNESIUM_MG = "MAGNESIUM_MG"
    MANGANESE_MG = "MANGANESE_MG"
    NIACIN_MG = "NIACIN_MG"
    PHOSPHORUS_MG = "PHOSPHORUS_MG"
    POTASSIUM_MG = "POTASSIUM_MG"
    PROTEIN_G = "PROTEIN_G"
    RIBOFLAVIN_MG = "RIBOFLAVIN_MG"
    SATURATED_FATS_G = "SATURATED_FATS_G"
    SELENIUM_MCG = "SELENIUM_MCG"
    SODIUM_MG = "SODIUM_MG"
    SUGAR_G = "SUGAR_G"
    THIAMIN_MG = "THIAMIN_MG"
    VITA_MCG = "VITA_MCG"
    VITB12_MCG = "VITB12_MCG"
    VITB6_MG = "VITB6_MG"
    VITC_MG = "VITC_MG"
    ZINC_MG = "ZINC_MG"

@define_snowflake_table(
    SNOWFLAKE_DATABASE="NUTRIRAG_PROJECT",
    SCHEMA_NAME="ENRICHED",
    TABLE_NAME="INGREDIENTS",
)
class CleanedIngredients(Table):
	NDB_NO = "NDB_NO"
	DESCRIP = "DESCRIP"
	ENERGY_KCAL = "ENERGY_KCAL"
	PROTEIN_G = "PROTEIN_G"
	SATURATED_FATS_G = "SATURATED_FATS_G"
	FAT_G = "FAT_G"
	CARB_G = "CARB_G"
	FIBER_G = "FIBER_G"
	SUGAR_G = "SUGAR_G"
	CALCIUM_MG = "CALCIUM_MG"
	IRON_MG = "IRON_MG"
	MAGNESIUM_MG = "MAGNESIUM_MG"
	PHOSPHORUS_MG = "PHOSPHORUS_MG"
	POTASSIUM_MG = "POTASSIUM_MG"
	SODIUM_MG = "SODIUM_MG"
	ZINC_MG = "ZINC_MG"
	COPPER_MCG = "COPPER_MCG"
	MANGANESE_MG = "MANGANESE_MG"
	SELENIUM_MCG = "SELENIUM_MCG"
	VITC_MG = "VITC_MG"
	THIAMIN_MG = "THIAMIN_MG"
	RIBOFLAVIN_MG = "RIBOFLAVIN_MG"
	NIACIN_MG = "NIACIN_MG"
	VITB6_MG = "VITB6_MG"
	FOLATE_MCG = "FOLATE_MCG"
	VITB12_MCG = "VITB12_MCG"
	VITA_MCG = "VITA_MCG"
	VITE_MG = "VITE_MG"
	VITD2_MCG = "VITD2_MCG"
	PCA_MICRO_1 = "PCA_MICRO_1"
	PCA_MICRO_2 = "PCA_MICRO_2"
	CLUSTER_MICRO = "CLUSTER_MICRO"
	DIST_MICRO_CENTROID = "DIST_MICRO_CENTROID"
	PCA_MACRO_1 = "PCA_MACRO_1"
	PCA_MACRO_2 = "PCA_MACRO_2"
	PCA_MACRO_3 = "PCA_MACRO_3"
	CLUSTER_MACRO = "CLUSTER_MACRO"
	DIST_MACRO_CENTROID = "DIST_MACRO_CENTROID"
	SCORE_SANTE = "SCORE_SANTE"
