"""Snowflake table definitions for RECIPES_SAMPLE_50K and RECIPES_50K_EMBEDDINGS tables."""

from typing import List
from shared.snowflake.tables.table import define_snowflake_table, Table


@define_snowflake_table(
    SNOWFLAKE_DATABASE="NUTRIRAG_PROJECT",
    SCHEMA_NAME="ENRICHED",
    TABLE_NAME="RECIPES_SAMPLE_50K",
)
class RecipesSample50kTable(Table):
    NAME = "NAME"
    ID = "ID"
    MINUTES = "MINUTES"
    CONTRIBUTOR_ID = "CONTRIBUTOR_ID"
    SUBMITTED = "SUBMITTED"
    TAGS = "TAGS"
    NUTRITION = "NUTRITION"
    N_STEPS = "N_STEPS"
    STEPS = "STEPS"
    DESCRIPTION = "DESCRIPTION"
    INGREDIENTS = "INGREDIENTS"
    N_INGREDIENTS = "N_INGREDIENTS"
    HAS_IMAGE = "HAS_IMAGE"
    IMAGE_URL = "IMAGE_URL"
    INGREDIENTS_RAW_STR = "INGREDIENTS_RAW_STR"
    SERVING_SIZE = "SERVING_SIZE"
    SERVINGS = "SERVINGS"
    SEARCH_TERMS = "SEARCH_TERMS"
    FILTERS = "FILTERS"
    SCORE_SANTE = "SCORE_SANTE"
    ENERGY_KCAL_100G = "ENERGY_KCAL_100G"
    PROTEIN_G_100G = "PROTEIN_G_100G"
    SATURATED_FATS_G_100G = "SATURATED_FATS_G_100G"
    FAT_G_100G = "FAT_G_100G"
    CARB_G_100G = "CARB_G_100G"
    FIBER_G_100G = "FIBER_G_100G"
    SUGAR_G_100G = "SUGAR_G_100G"
    SODIUM_MG_100G = "SODIUM_MG_100G"
    CALCIUM_MG_100G = "CALCIUM_MG_100G"
    IRON_MG_100G = "IRON_MG_100G"
    POTASSIUM_MG_100G = "POTASSIUM_MG_100G"
    VITC_MG_100G = "VITC_MG_100G"
    MAGNESIUM_MG_100G = "MAGNESIUM_MG_100G"

    @staticmethod
    def get_columns_to_concat_for_embedding() -> List["RecipesSample50kTable"]:
        return [
            RecipesSample50kTable.NAME,
            RecipesSample50kTable.TAGS,
            RecipesSample50kTable.SEARCH_TERMS,
            RecipesSample50kTable.INGREDIENTS,
            RecipesSample50kTable.DESCRIPTION,
        ]


@define_snowflake_table(
    SNOWFLAKE_DATABASE="NUTRIRAG_PROJECT",
    SCHEMA_NAME="VECTORS",
    TABLE_NAME="RECIPES_50K_EMBEDDINGS",
)
class Recipes50kEmbeddingsTable(Table):
    # Common columns with RecipesSample50kTable
    NAME = "NAME"
    ID = "ID"
    MINUTES = "MINUTES"
    CONTRIBUTOR_ID = "CONTRIBUTOR_ID"
    SUBMITTED = "SUBMITTED"
    TAGS = "TAGS"
    NUTRITION = "NUTRITION"
    N_STEPS = "N_STEPS"
    STEPS = "STEPS"
    DESCRIPTION = "DESCRIPTION"
    INGREDIENTS = "INGREDIENTS"
    N_INGREDIENTS = "N_INGREDIENTS"
    HAS_IMAGE = "HAS_IMAGE"
    IMAGE_URL = "IMAGE_URL"
    INGREDIENTS_RAW_STR = "INGREDIENTS_RAW_STR"
    SERVING_SIZE = "SERVING_SIZE"
    SERVINGS = "SERVINGS"
    SEARCH_TERMS = "SEARCH_TERMS"
    FILTERS = "FILTERS"
    SCORE_SANTE = "SCORE_SANTE"
    ENERGY_KCAL_100G = "ENERGY_KCAL_100G"
    PROTEIN_G_100G = "PROTEIN_G_100G"
    SATURATED_FATS_G_100G = "SATURATED_FATS_G_100G"
    FAT_G_100G = "FAT_G_100G"
    CARB_G_100G = "CARB_G_100G"
    FIBER_G_100G = "FIBER_G_100G"
    SUGAR_G_100G = "SUGAR_G_100G"
    SODIUM_MG_100G = "SODIUM_MG_100G"
    CALCIUM_MG_100G = "CALCIUM_MG_100G"
    IRON_MG_100G = "IRON_MG_100G"
    POTASSIUM_MG_100G = "POTASSIUM_MG_100G"
    VITC_MG_100G = "VITC_MG_100G"
    MAGNESIUM_MG_100G = "MAGNESIUM_MG_100G"

    # Embedding columns
    CONCATENATED_TEXT_FOR_RAG = "CONCATENATED_TEXT_FOR_RAG"
    EMBEDDING = "EMBEDDING"
