"""Snowflake table definitions for RECIPES_SAMPLE_50K tables."""

from typing import List

from shared.snowflake.tables.table import define_snowflake_table, Table

@define_snowflake_table(
    SNOWFLAKE_DATABASE="NUTRIRAG_PROJECT",
    SCHEMA_NAME="ENRICHED",
    TABLE_NAME="RECIPES_SAMPLE_50K",
)
class RecipesFullTable(Table):
    NAME = "NAME"
    ID = "ID"
    MINUTES = "MINUTES"
    CONTRIBUTOR_ID = "CONTRIBUTOR_ID"
    SUBMITTED = "SUBMITTED"
    TAGS = "TAGS"
    NUTRITION = "NUTRITION"
    N_STEPS = "N_STEPS"
    STEPS = "STEPS"
    DESCRIPTION = "DESCRIPTION"
    INGREDIENTS = "INGREDIENTS"
    N_INGREDIENTS = "N_INGREDIENTS"
    HAS_IMAGE = "HAS_IMAGE"
    IMAGE_URL = "IMAGE_URL"
    INGREDIENTS_RAW_STR = "INGREDIENTS_RAW_STR"
    SERVING_SIZE = "SERVING_SIZE"
    SERVINGS = "SERVINGS"
    SEARCH_TERMS = "SEARCH_TERMS"
    FILTERS = "FILTERS"
    SCORE_SANTE = "SCORE_SANTE"
    ENERGY_KCAL_100G = "ENERGY_KCAL_100G"
    PROTEIN_G_100G = "PROTEIN_G_100G"
    SATURATED_FATS_G_100G = "SATURATED_FATS_G_100G"
    FAT_G_100G = "FAT_G_100G"
    CARB_G_100G = "CARB_G_100G"
    FIBER_G_100G = "FIBER_G_100G"
    SUGAR_G_100G = "SUGAR_G_100G"
    SODIUM_MG_100G = "SODIUM_MG_100G"
    CALCIUM_MG_100G = "CALCIUM_MG_100G"
    IRON_MG_100G = "IRON_MG_100G"
    POTASSIUM_MG_100G = "POTASSIUM_MG_100G"
    VITC_MG_100G = "VITC_MG_100G"
    MAGNESIUM_MG_100G = "MAGNESIUM_MG_100G"