-- NutriRAG SCHEMA IF NOT EXISTS Creation Script
-- This script uses environment variables for flexibility
-- Usage: Replace ${WAREHOUSE_NAME} and ${DATABASE_NAME} with actual values
-- Or use with a script that substitutes these variables

-- Create Warehouse
CREATE WAREHOUSE IF NOT EXISTS ${WAREHOUSE_NAME};

-- Create Database
CREATE DATABASE IF NOT EXISTS ${DATABASE_NAME};

-- Create RAW
CREATE SCHEMA IF NOT EXISTS RAW WITH managed access;

CREATE TABLE IF NOT EXISTS ${DATABASE_NAME}.RAW.CLEANED_INGREDIENTS (
	NDB_NO VARCHAR(16777216),
	DESCRIP VARCHAR(16777216),
	ENERGY_KCAL NUMBER(38,15),
	PROTEIN_G NUMBER(38,2),
	SATURATED_FATS_G NUMBER(38,18),
	FAT_G NUMBER(38,2),
	CARB_G NUMBER(38,2),
	FIBER_G NUMBER(38,2),
	SUGAR_G NUMBER(38,2),
	CALCIUM_MG NUMBER(38,18),
	IRON_MG NUMBER(38,3),
	PHOSPHORUS_MG NUMBER(38,2),
	POTASSIUM_MG NUMBER(38,2),
	SODIUM_MG NUMBER(38,2),
	ZINC_MG NUMBER(38,2),
	COPPER_MCG NUMBER(38,18),
	MANGANESE_MG NUMBER(38,18),
	SELENIUM_MCG NUMBER(38,2),
	VITC_MG NUMBER(38,2),
	THIAMIN_MG NUMBER(38,18),
	RIBOFLAVIN_MG NUMBER(38,18),
	NIACIN_MG NUMBER(38,18),
	VITB6_MG NUMBER(38,18),
	FOLATE_MCG NUMBER(38,2),
	VITB12_MCG NUMBER(38,2),
	VITA_MCG NUMBER(38,2),
	VITE_MG NUMBER(38,2),
	VITD2_MCG NUMBER(38,2),
	MAGNESIUM_MG FLOAT
);


-- Cleaned
CREATE SCHEMA IF NOT EXISTS CLEANED;

CREATE TABLE IF NOT EXISTS ${DATABASE_NAME}.CLEANED.INGREDIENTS_MATCHING (
	ID NUMBER(38,0),
	INGREDIENT VARCHAR(16777216),
	NDB_NO VARCHAR(16777216)
);

CREATE TABLE IF NOT EXISTS ${DATABASE_NAME}.CLEANED.INGREDIENTS_QUANTITY (
	ID NUMBER(38,0),
	INGREDIENTS VARCHAR(16777216),
	QUANTITY_RAW_STR VARCHAR(16777216),
	QUANTITY NUMBER(38,3),
	UNIT VARCHAR(16777216),
	QTY_ML NUMBER(38,17),
	QTY_G NUMBER(38,17)
);

CREATE TABLE IF NOT EXISTS ${DATABASE_NAME}.CLEANED.INGREDIENTS_TAGGED (
	NDB_NO VARCHAR(16777216),
	DESCRIP VARCHAR(16777216),
	FOODON_LABEL VARCHAR(16777216),
	IS_DAIRY BOOLEAN,
	IS_SEAFOOD BOOLEAN,
	IS_GLUTEN BOOLEAN,
	IS_VEGETABLE BOOLEAN,
	CONTAINS_NUTS BOOLEAN,
	IS_SWEETENER BOOLEAN,
	IS_VEGETARIAN BOOLEAN,
	IS_GRAIN BOOLEAN
);

CREATE TABLE IF NOT EXISTS ${DATABASE_NAME}.CLEANED.RECIPES_SAMPLE_50K (
	NAME VARCHAR(16777216),
	ID NUMBER(38,0),
	MINUTES NUMBER(38,0),
	CONTRIBUTOR_ID NUMBER(38,0),
	SUBMITTED DATE,
	TAGS ARRAY,
	NUTRITION ARRAY,
	N_STEPS NUMBER(38,0),
	STEPS ARRAY,
	DESCRIPTION VARCHAR(16777216),
	INGREDIENTS ARRAY,
	N_INGREDIENTS NUMBER(38,0),
	HAS_IMAGE NUMBER(38,0),
	IMAGE_URL VARCHAR(16777216),
	INGREDIENTS_RAW_STR ARRAY,
	SERVING_SIZE VARCHAR(16777216),
	SERVINGS NUMBER(38,0),
	SEARCH_TERMS ARRAY,
	FILTERS ARRAY
);

-- Enriched
CREATE SCHEMA IF NOT EXISTS ENRICHED;

CREATE TABLE IF NOT EXISTS ${DATABASE_NAME}.ENRICHED.RECIPES_SAMPLE_50K (
	NAME VARCHAR(16777216),
	ID NUMBER(38,0),
	MINUTES NUMBER(38,0),
	CONTRIBUTOR_ID NUMBER(38,0),
	SUBMITTED DATE,
	TAGS ARRAY,
	NUTRITION ARRAY,
	N_STEPS NUMBER(38,0),
	STEPS ARRAY,
	DESCRIPTION VARCHAR(16777216),
	INGREDIENTS ARRAY,
	N_INGREDIENTS NUMBER(38,0),
	HAS_IMAGE NUMBER(38,0),
	IMAGE_URL VARCHAR(16777216),
	INGREDIENTS_RAW_STR ARRAY,
	SERVING_SIZE VARCHAR(16777216),
	SERVINGS NUMBER(38,0),
	SEARCH_TERMS ARRAY,
	FILTERS ARRAY,
	SCORE_SANTE FLOAT,
	ENERGY_KCAL_100G FLOAT,
	PROTEIN_G_100G FLOAT,
	SATURATED_FATS_G_100G FLOAT,
	FAT_G_100G FLOAT,
	CARB_G_100G FLOAT,
	FIBER_G_100G FLOAT,
	SUGAR_G_100G FLOAT,
	SODIUM_MG_100G FLOAT,
	CALCIUM_MG_100G FLOAT,
	IRON_MG_100G FLOAT,
	POTASSIUM_MG_100G FLOAT,
	VITC_MG_100G FLOAT,
	MAGNESIUM_MG_100G FLOAT
);

CREATE TABLE IF NOT EXISTS ${DATABASE_NAME}.ENRICHED.INGREDIENTS (
	NDB_NO VARCHAR(16777216),
	DESCRIP VARCHAR(16777216),
	ENERGY_KCAL NUMBER(38,15),
	PROTEIN_G NUMBER(38,2),
	SATURATED_FATS_G NUMBER(38,16),
	FAT_G NUMBER(38,2),
	CARB_G NUMBER(38,2),
	FIBER_G NUMBER(38,2),
	SUGAR_G NUMBER(38,2),
	CALCIUM_MG NUMBER(38,16),
	IRON_MG NUMBER(38,3),
	MAGNESIUM_MG NUMBER(38,2),
	PHOSPHORUS_MG NUMBER(38,2),
	POTASSIUM_MG NUMBER(38,2),
	SODIUM_MG NUMBER(38,2),
	ZINC_MG NUMBER(38,2),
	COPPER_MCG NUMBER(38,16),
	MANGANESE_MG NUMBER(38,16),
	SELENIUM_MCG NUMBER(38,2),
	VITC_MG NUMBER(38,2),
	THIAMIN_MG NUMBER(38,16),
	RIBOFLAVIN_MG NUMBER(38,16),
	NIACIN_MG NUMBER(38,16),
	VITB6_MG NUMBER(38,16),
	FOLATE_MCG NUMBER(38,2),
	VITB12_MCG NUMBER(38,2),
	VITA_MCG NUMBER(38,2),
	VITE_MG NUMBER(38,2),
	VITD2_MCG NUMBER(38,0),
	PCA_MICRO_1 NUMBER(38,0),
	PCA_MICRO_2 NUMBER(38,20),
	CLUSTER_MICRO NUMBER(38,0),
	DIST_MICRO_CENTROID NUMBER(38,18),
	PCA_MACRO_1 NUMBER(38,20),
	PCA_MACRO_2 NUMBER(38,19),
	PCA_MACRO_3 NUMBER(38,20),
	CLUSTER_MACRO NUMBER(38,0),
	DIST_MACRO_CENTROID NUMBER(38,17),
	SCORE_SANTE FLOAT
);

-- Analytics
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

CREATE TABLE IF NOT EXISTS ${DATABASE_NAME}.ANALYTICS.HIST_SEARCH (
	ROW_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	CONVERSATION_ID VARCHAR(16777216),
	USER_ID VARCHAR(16777216),
	QUERY VARCHAR(16777216),
	TOTAL_FOUND NUMBER(38,0),
	EXECUTION_TIME_MS FLOAT,
	SEARCH_STATUS VARCHAR(16777216),
	SEARCH_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	RECIPE_ID NUMBER(38,0),
	NAME VARCHAR(16777216),
	MINUTES NUMBER(38,0),
	N_INGREDIENTS NUMBER(38,0),
	N_STEPS NUMBER(38,0),
	RATING_AVG FLOAT,
	RATING_COUNT NUMBER(38,0),
	CALORIES FLOAT,
	PROTEIN_G FLOAT,
	FAT_G FLOAT,
	CARBS_G FLOAT,
	SCORE_HEALTH FLOAT,
	RAW_RECIPE_JSON VARIANT,
	primary key (ROW_ID)
);

CREATE TABLE IF NOT EXISTS ${DATABASE_NAME}.ANALYTICS.HIST_TRANSFORMATIONS (
    TRANSFORM_ID        INTEGER IDENTITY(1,1) PRIMARY KEY,
    CONVERSATION_ID     VARCHAR,
    USER_ID             VARCHAR,
    ORIGINAL_NAME       STRING,
    TRANSFORMED_NAME    STRING,
    SUCCESS             BOOLEAN,
    MESSAGE             STRING,
    TRANSFORM_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    NUTRITION_BEFORE    VARIANT,
    NUTRITION_AFTER     VARIANT,
    SUBSTITUTIONS       VARIANT,
    ORIGINAL_RECIPE     VARIANT,
    NEW_RECIPE          VARIANT, 
    FULL_RESPONSE_JSON  VARIANT
);

CREATE TABLE IF NOT EXISTS ${DATABASE_NAME}.ANALYTICS.INGREDIENTS_WITH_CLUSTERS (
	NDB_NO VARCHAR(16777216),
	DESCRIP VARCHAR(16777216),
	ENERGY_KCAL NUMBER(38,15),
	PROTEIN_G NUMBER(38,2),
	SATURATED_FATS_G NUMBER(38,16),
	FAT_G NUMBER(38,2),
	CARB_G NUMBER(38,2),
	FIBER_G NUMBER(38,2),
	SUGAR_G NUMBER(38,2),
	CALCIUM_MG NUMBER(38,16),
	IRON_MG NUMBER(38,3),
	MAGNESIUM_MG NUMBER(38,2),
	PHOSPHORUS_MG NUMBER(38,2),
	POTASSIUM_MG NUMBER(38,2),
	SODIUM_MG NUMBER(38,2),
	ZINC_MG NUMBER(38,2),
	COPPER_MCG NUMBER(38,16),
	MANGANESE_MG NUMBER(38,16),
	SELENIUM_MCG NUMBER(38,2),
	VITC_MG NUMBER(38,2),
	THIAMIN_MG NUMBER(38,16),
	RIBOFLAVIN_MG NUMBER(38,16),
	NIACIN_MG NUMBER(38,16),
	VITB6_MG NUMBER(38,16),
	FOLATE_MCG NUMBER(38,2),
	VITB12_MCG NUMBER(38,2),
	VITA_MCG NUMBER(38,2),
	VITE_MG NUMBER(38,2),
	VITD2_MCG NUMBER(38,0),
	PCA_MICRO_1 NUMBER(38,0),
	PCA_MICRO_2 NUMBER(38,20),
	CLUSTER_MICRO NUMBER(38,0),
	DIST_MICRO_CENTROID NUMBER(38,18),
	PCA_MACRO_1 NUMBER(38,20),
	PCA_MACRO_2 NUMBER(38,19),
	PCA_MACRO_3 NUMBER(38,20),
	CLUSTER_MACRO NUMBER(38,0),
	DIST_MACRO_CENTROID NUMBER(38,17)
);
create or replace TABLE ${DATABASE_NAME}.ANALYTICS.RECIPES_SAMPLE_50K_WITH_CLUSTER (
	NAME VARCHAR(16777216),
	ID NUMBER(38,0),
	MINUTES NUMBER(38,0),
	CONTRIBUTOR_ID NUMBER(38,0),
	SUBMITTED DATE,
	TAGS ARRAY,
	NUTRITION ARRAY,
	N_STEPS NUMBER(38,0),
	STEPS ARRAY,
	DESCRIPTION VARCHAR(16777216),
	INGREDIENTS ARRAY,
	N_INGREDIENTS NUMBER(38,0),
	HAS_IMAGE NUMBER(38,0),
	IMAGE_URL VARCHAR(16777216),
	INGREDIENTS_RAW_STR ARRAY,
	SERVING_SIZE NUMBER(38,0),
	SERVINGS NUMBER(38,0),
	SEARCH_TERMS ARRAY,
	FILTERS ARRAY,
	NUTRISCORE ARRAY,
	SCORE_SANTE FLOAT,
	CLUSTER_KM NUMBER(38,0),
	X FLOAT,
	Y FLOAT
);
-- Public 
CREATE SCHEMA IF NOT EXISTS PUBLIC;

-- 1. Create CONVERSATIONS Table
CREATE TABLE IF NOT EXISTS ${DATABASE_NAME}.PUBLIC.CONVERSATIONS (
    ID VARCHAR(16777216) DEFAULT UUID_STRING() PRIMARY KEY,
    USER_ID VARCHAR(16777216) NOT NULL,
    TITLE VARCHAR(16777216),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- 2. Create MESSAGES Table (Updated with Metadata Column)
CREATE TABLE IF NOT EXISTS ${DATABASE_NAME}.PUBLIC.MESSAGES (
    ID VARCHAR(16777216) DEFAULT UUID_STRING() PRIMARY KEY,
    CONVERSATION_ID VARCHAR(16777216) NOT NULL,
    ROLE VARCHAR(16777216) NOT NULL, 
    CONTENT VARCHAR(16777216) NOT NULL,
    THREAD_ID INTEGER NULL, 
    MESSAGE_ID INTEGER NULL,

    
    -- Added metadata column for structured context
    METADATA VARIANT COMMENT 'JSON metadata for storing recipe IDs, search queries, and other structured context',
    
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    
    -- Foreign key constraint
    CONSTRAINT FK_MESSAGES_CONVERSATION 
        FOREIGN KEY (CONVERSATION_ID) 
        REFERENCES ${DATABASE_NAME}.PUBLIC.CONVERSATIONS(ID)
        ON DELETE CASCADE
);

-- 3. Create USER_SESSIONS Table
CREATE TABLE IF NOT EXISTS ${DATABASE_NAME}.PUBLIC.USER_SESSIONS (
    TOKEN_HASH VARCHAR(16777216) NOT NULL PRIMARY KEY,
    USERNAME VARCHAR(16777216) NOT NULL,
    EXPIRES_AT TIMESTAMP_NTZ(9) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE SCHEMA IF NOT EXISTS SERVICES;

-- 1. Créer la règle réseau
CREATE OR REPLACE NETWORK RULE training_internet_rule
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = ('0.0.0.0:443', '0.0.0.0:80')
  COMMENT = 'Règle réseau autorisant les connexions sortantes HTTPS (port 443) et HTTP (port 80) vers toutes les destinations Internet. Utilisée pour permettre aux UDF Python d''effectuer des appels API externes.';


-- 2. Créer l'intégration
CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION training_internet_access
  ALLOWED_NETWORK_RULES = (training_internet_rule)
  ENABLED = TRUE
  COMMENT = 'Intégration d''accès externe pour les UDF Python. Permet aux fonctions Python dans Snowflake de faire des requêtes HTTP/HTTPS vers des APIs externes via la règle training_internet_rule.';


-- 3. Accorder l'accès au rôle
GRANT USAGE ON INTEGRATION training_internet_access TO ROLE ${ROLE};